meta_product_name: "FliQ"
meta_title: "FliQ - Whenever, whereever, with whomever, play ping-pong with FliQ!"
meta_description: "FliQ connects friendly ping-pong players from all different backrounds with a click of a button. find players, create matches, improve your ranking!"
meta_image: "favicon-32x32.png" 
